### PR TITLE
Deploy nodejs express app connected to mongodb database to AWS Lambda function

### PR DESCRIPTION
**Pull request by MichaelPetersIduku**
Deploy to aws Lambda

### CODE REVIEW

**Comment by MichaelPetersIduku** [comment]
@Akinolae @kvngcheerio check this out

Base url: [https://0r5ri1zup8.execute-api.eu-west-2.amazonaws.com](https://0r5ri1zup8.execute-api.eu-west-2.amazonaws.com)

**Comment by Akinolae** [comment]
> @Akinolae @kvngcheerio check this out
> 
> Base url: [https://0r5ri1zup8.execute-api.eu-west-2.amazonaws.com](https://0r5ri1zup8.execute-api.eu-west-2.amazonaws.com)

I'll check it out

**Comment by kvngcheerio** [comment]
Its actually working! I don fork am oh

**Comment by MichaelPetersIduku** [comment]
Nice

**Comment by Akinolae** [comment]
@MichaelPetersIduku is there a reason you called it inside `app.use()` . can't the server work without using it that way?

**Comment by MichaelPetersIduku** [comment]
@Akinolae because its been deployed on lambda, it has to be added to the express middleware. Else the mongodb connection would remain on connecting state and won't be up when you try to create an entry or read from the database

**Comment by Akinolae** [comment]
@MichaelPetersIduku ohh cool. got it man!. Thanks

**Pull request merged**
